# init.ll - VRS node configuration and service startup
#
# Minato is a dedicated background-indexing node. Other nodes initiate the
# full-duplex connection and run the interactive, machine-local services.
(if (eq? (node_name) "minato")
    (begin
      (run "./scripts/feedbin.ll")
      (run "./scripts/oura.ll"))
    (begin
      (configure :nodes '("ssh://minato"))
      (run "./scripts/chat.ll")
      (run "./scripts/system_appearance.ll")
      (run "./scripts/todos.ll")
      (run "./scripts/cmd_macro.ll")
      (run "./scripts/interfacegen.ll")
      (run "./scripts/os_maps.ll")
      (run "./scripts/os_notes.ll")
      (run "./scripts/obsidian.ll")
      (run "./scripts/os_display.ll")
      (run "./scripts/os_window.ll")
      (run "./scripts/os_notify.ll")
      (run "./scripts/os_browser.ll")
      (run "./scripts/os_screencap.ll")
      (run "./scripts/os_cal.ll")
      (run "./scripts/os_clipboard.ll")
      (run "./scripts/github.ll")
      (run "./scripts/safari_history.ll")
      (run "./scripts/youtube.ll")
      (run "./scripts/stickies.ll")
      (run "./scripts/eden.ll")
      (run "./scripts/rlist.ll")
      (run "./scripts/nl_shell.ll")
      (run "./scripts/nl_scheduler.ll")
      (run "./scripts/vrs_shell_refresh.ll")
      (run "./scripts/vrsjmp.ll")))
