[package]
name = "vrsctl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vrs = { path = "../libvrs" }
lemma = { path = "../lemma" }
tokio = { version = "1.32.0", features = ["full"] }
anyhow = "1.0.75"
tracing-subscriber = "0.3.17"
tracing = "0.1.37"
clap = { version = "4.4.4", features = ["cargo", "derive"] } 
rustyline = { version = "12.0.0", features = ["derive"] }
dirs = "5.0.1"

