[package]
name = "vrsjmp"
version = "0.0.0"
description = "VRS desktop command palette"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-global-shortcut = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1.40"
vrs = { path = "../../libvrs" }
lyric = { path = "../../lyric" }
anyhow = "1.0.89"
clap = { version = "4.5", features = ["derive"] }
tokio = "1.40"

[features]
# Embed the built frontend when running outside the Tauri dev server.
custom-protocol = ["tauri/custom-protocol"]
